settings:
  title: 'FiO Status Page'
  url: 'https://status.fio.one' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: fio-one
    name: www.fio.one
    description: 'Transforming Businesses With Trustworthy Blockchain Automation'
    url: 'https://www.fio.one'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: fio-io # unique identifier
    name: console.fio.io
    description: '' # default=empty
    url: 'https://console.fio.one/health' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
